import type { CheatSheetData } from './index'

export const linuxCommands: CheatSheetData = {
  id: 'linux',
  name: 'Linux 常用命令',
  description: '文件操作、进程管理、网络、权限、文本处理等高频 Linux 命令速查',
  columns: [
    { key: 'command', label: '命令', width: '240px', copyable: true },
    { key: 'category', label: '分类', width: '100px' },
    { key: 'params', label: '常用参数', width: '200px' },
    { key: 'description', label: '说明' },
  ],
  rows: [
    // === 文件操作 ===
    { command: 'ls [选项] [路径]', category: '文件', params: '-l 详细; -a 隐藏; -h 人类可读; -r 反向; -t 按时间', description: '列出目录内容', examples: ['ls -lah', 'ls -l /etc | head', 'ls -laRt'] },
    { command: 'cd [目录]', category: '文件', params: '无参数回用户主目录; .. 上级; - 上一个目录', description: '切换工作目录', examples: ['cd /var/log', 'cd ../..', 'cd -'] },
    { command: 'pwd', category: '文件', params: '-P 物理路径(解析软链接)', description: '显示当前工作目录', examples: ['pwd'] },
    { command: 'mkdir [选项] 目录', category: '文件', params: '-p 递归创建; -m 权限(如 755)', description: '创建目录', examples: ['mkdir -p src/{components,views}', 'mkdir -m 700 data'] },
    { command: 'rm [选项] 文件/目录', category: '文件', params: '-r 递归; -f 强制; -i 交互; -v 详细', description: '删除文件或目录（谨慎使用）', examples: ['rm file.txt', 'rm -rf /tmp/cache', 'rm -i *.bak'] },
    { command: 'cp [选项] 源 目标', category: '文件', params: '-r 递归; -f 强制覆盖; -n 不覆盖; -a 保留属性(=dR); -v 详细', description: '复制文件或目录', examples: ['cp file.txt /backup/', 'cp -av src/ dist/'] },
    { command: 'mv [选项] 源 目标', category: '文件', params: '-f 强制; -i 交互; -n 不覆盖; -v 详细', description: '移动/重命名文件或目录', examples: ['mv file.txt file.txt.bak', 'mv dir/ /tmp/', 'mv *.log logs/'] },
    { command: 'touch 文件', category: '文件', params: '-d 日期(如 "2 days ago"); -a 仅修改访问时间', description: '创建空文件或修改时间戳', examples: ['touch newfile.txt', 'touch -d "2024-01-01" file.txt'] },
    { command: 'cat [选项] 文件', category: '文件', params: '-n 行号; -A 显示所有字符; -b 非空行号', description: '查看文件内容（适合小文件）', examples: ['cat /etc/hosts', 'cat -n log.txt | tail -20'] },
    { command: 'head [-n N] 文件', category: '文件', params: '-n N 前 N 行(默认10); -c N 前 N 字节; -f 持续追踪', description: '查看文件开头', examples: ['head -50 /var/log/syslog', 'head -c 1024 binary.bin'] },
    { command: 'tail [-n N] 文件', category: '文件', params: '-n N 末 N 行(默认10); -f 实时追踪; -F 带文件重建; -c N 末 N 字节', description: '查看文件末尾（日志调试神器）', examples: ['tail -f /var/log/nginx/error.log', 'tail -n 100 app.log'] },
    { command: 'less [选项] 文件', category: '文件', params: '-N 行号; -i 忽略大小写搜索; -S 不自动换行; -F -X 小文件自动退出', description: '分页查看器（比 more 功能强）', examples: ['less +F /var/log/syslog', 'less -N huge.txt'] },
    { command: 'wc [选项] 文件', category: '文件', params: '-l 行数; -w 单词数; -c 字节; -m 字符', description: '统计行数/字数/字节数', examples: ['wc -l access.log', 'find . | wc -l'] },
    { command: 'find 路径 [选项] [动作]', category: '文件', params: '-name "*.log"; -type f/d; -size +10M; -mtime -7(7天内); -exec rm {} \\;', description: '在目录树中搜索文件（功能强大）', examples: ['find /var/log -name "*.log" -size +100M', 'find . -type f -name "*.py" -exec wc -l {} +'] },
    { command: 'du [选项] [路径]', category: '文件', params: '-h 人类可读; -s 仅总计; -d N 深度; --max-depth=N', description: '磁盘使用量统计', examples: ['du -sh /var/lib/docker', 'du -d 1 /home | sort -h'] },
    { command: 'df [选项] [文件系统]', category: '文件', params: '-h 人类可读; -T 文件系统类型; -x 排除类型', description: '显示文件系统磁盘使用情况', examples: ['df -h', 'df -hT /dev/sda1'] },
    { command: 'ln -s 目标 链接名', category: '文件', params: '-s 软链接; 无 -s 硬链接; -f 强制覆盖', description: '创建软/硬链接', examples: ['ln -s /usr/local/bin/python3 /usr/bin/python', 'ln -sf ~/dotfiles/.zshrc ~/.zshrc'] },
    { command: 'file 文件', category: '文件', params: '-i MIME 类型; -z 压缩文件内部', description: '检测文件类型', examples: ['file image.png', 'file -i data.json'] },
    { command: 'chmod 权限 文件', category: '权限', params: 'u+w 所有者加写; g+x 组加执行; o-rwx 其他无; 755=111/101/101', description: '修改文件权限', examples: ['chmod +x script.sh', 'chmod 755 dir/ && chmod 644 dir/*', 'chmod -R 600 ~/.ssh'] },
    { command: 'chown 用户[:组] 文件', category: '权限', params: '-R 递归; --reference=FILE 参考文件', description: '修改文件所有者/组', examples: ['chown -R www-data:www-data /var/www', 'chown root:root /etc/passwd'] },
    { command: 'passwd [用户名]', category: '权限', params: '-d 删除密码(空密码); -e 强制过期; -l 锁定; -u 解锁', description: '修改用户密码', examples: ['passwd', 'passwd root'] },
    { command: 'su [-] 用户名', category: '权限', params: '- 加载登录环境; -c "cmd" 执行命令后返回', description: '切换用户身份', examples: ['su -', 'su - postgres -c "pg_ctl status"'] },
    { command: 'sudo [选项] 命令', category: '权限', params: '-i 模拟登录shell; -s 模拟shell; -u USER 指定用户; -v 刷新密码; -k 撤销缓存', description: '以 root/其他用户身份执行命令', examples: ['sudo apt update', 'sudo -u www-data ls -la /var/www', 'sudo !!'] },
    // === 进程管理 ===
    { command: 'ps [选项]', category: '进程', params: 'aux 所有用户全格式; ef 完整参数列表; -efH 树状; -eo pid,user,%cpu,%mem,cmd', description: '查看进程状态', examples: ['ps aux | grep nginx', 'ps -efH | head -20', 'ps -eo pid,user,%cpu,%mem,cmd --sort=-%cpu | head'] },
    { command: 'top / htop', category: '进程', params: 'top: -p PID 监控指定; -d 秒 刷新间隔; htop: 交互更友好', description: '实时进程监控', examples: ['top', 'top -d 1 -p 1234,5678', 'htop'] },
    { command: 'kill [-信号] PID', category: '进程', params: '-9 强杀(SIGKILL); -15 正常终止(SIGTERM,默认); -2 Ctrl+C(SIGINT); -1 HUP重载配置', description: '发送信号终止/管理进程', examples: ['kill 1234', 'kill -9 $(pgrep -f "node app")', 'kill -HUP $(cat nginx.pid)'] },
    { command: 'pkill / pgrep 模式', category: '进程', params: 'pkill -9 name; pgrep -af name; pgrep -u USER name', description: '按名称/命令模式查找/终止进程', examples: ['pgrep -af java', 'pkill -f "python main.py"', 'pkill -9 -u www-data'] },
    { command: 'nohup 命令 [&]', category: '进程', params: '输出默认追加 nohup.out; > out.log 2>&1 重定向', description: '后台运行不挂断（终端关闭也继续）', examples: ['nohup python server.py > server.log 2>&1 &', 'nohup java -jar app.jar &'] },
    { command: 'systemctl [子命令] 服务', category: '进程', params: 'start/stop/restart/status/enable/disable; daemon-reload 重载; list-units', description: 'systemd 服务管理', examples: ['systemctl status nginx', 'systemctl enable --now docker', 'systemctl daemon-reload && systemctl restart myapp'] },
    // === 网络 ===
    { command: 'ip [子命令] [选项]', category: '网络', params: 'addr link route neigh; a(addr) l(link) r(route); -br 简洁输出; -c 彩色', description: '现代网络管理命令（替代 ifconfig/route）', examples: ['ip -br addr', 'ip link set eth0 down', 'ip route add default via 192.168.1.1'] },
    { command: 'ss [选项]', category: '网络', params: '-t TCP; -u UDP; -l 监听; -n 数字; -p 进程; -s 统计', description: '查看套接字/端口连接（替代 netstat）', examples: ['ss -tlnp', 'ss -tulpn | grep LISTEN', 'ss -s'] },
    { command: 'curl [选项] URL', category: '网络', params: '-v 详细; -s 静默; -X POST; -d "data"; -H "Header: val"; -o 输出文件; -I 仅头; -L 跟踪跳转', description: 'HTTP/URL 请求工具', examples: ['curl -I https://example.com', 'curl -v -X POST -d \'{"k":"v"}\' -H "Content-Type: application/json" api.io/data', 'curl -L -o page.html https://example.com'] },
    { command: 'wget [选项] URL', category: '网络', params: '-c 断点续传; -b 后台; -O 文件; --no-check-certificate', description: '文件下载工具', examples: ['wget -c https://example.com/bigfile.iso', 'wget -O logo.png https://cdn.com/logo.png'] },
    { command: 'ping [选项] 主机', category: '网络', params: '-c N 发送次数; -W 超时秒; -s 包大小; -f 洪泛', description: '测试网络连通性', examples: ['ping -c 4 8.8.8.8', 'ping -i 0.5 host.com'] },
    { command: 'traceroute 主机', category: '网络', params: '-m 最大跳数; -n 不反查主机名; -w 等待秒', description: '追踪路由路径', examples: ['traceroute -n google.com', 'tracepath -n 1.1.1.1'] },
    // === 文本处理 ===
    { command: 'grep [选项] 模式 文件', category: '文本', params: '-r 递归; -n 行号; -i 忽略大小写; -v 反向; -E 扩展正则; -w 整词; -A N/B N/C N 上下文', description: '文本搜索（最常用命令之一）', examples: ['grep -rn "TODO" --include="*.ts" src/', 'grep -v "^#\\|^$" /etc/hosts', 'grep -A 3 "error" log.txt | head -20'] },
    { command: 'sed [选项] 脚本 文件', category: '文本', params: '-e 脚本; -i 原地修改; -r 扩展正则; -n 静默(配合p); s/旧/新/g 替换', description: '流式文本编辑器（替换/删除/插入）', examples: ["sed -i 's/old/new/g' file.txt", "sed -n '10,20p' log.txt", "sed -i '/^#/d; /^$/d' config.ini"] },
    { command: 'awk [选项] 程序 文件', category: '文本', params: '-F 分隔符; -f 脚本文件; -v 变量=值; $1 $2 字段引用; NR 行号', description: '强大的文本处理/列提取工具', examples: ['awk -F: \'{print $1, $6}\' /etc/passwd', 'df -h | awk \'NR>1 {print $5, $6}\'', 'awk \'{sum+=$3} END {print sum}\' data.csv'] },
    { command: 'sort [选项] 文件', category: '文本', params: '-n 数值; -r 反向; -k N,M 指定列; -t 分隔符; -u 去重; -h 人类可读(10K,2M)', description: '排序', examples: ['sort -n file.txt', 'df -h | sort -k5 -h', 'cat access.log | awk \'{print $1}\' | sort | uniq -c | sort -rn | head -10'] },
    { command: 'uniq [选项] [文件]', category: '文本', params: '-c 计数; -d 仅重复; -u 仅唯一; -i 忽略大小写; -f N 跳过前N字段', description: '去除/统计相邻重复行（注意：要先 sort）', examples: ['sort file.txt | uniq -c | sort -rn', 'cat log.txt | cut -d: -f1 | sort | uniq -c | sort -rn'] },
    { command: 'cut [选项] 文件', category: '文本', params: '-d 分隔符; -f 字段; -c 字符范围; -b 字节范围', description: '提取字段/字符', examples: ['cut -d: -f1 /etc/passwd', 'cut -c 1-50 longline.txt', 'ps aux | cut -c 1-15'] },
    { command: 'xargs [选项] [命令]', category: '文本', params: '-n N 每次传N个; -I {} 替换符; -p 确认; -t 打印执行; -P N 并行', description: '从标准输入构建命令参数', examples: ['find . -name "*.tmp" | xargs rm -f', 'cat urls.txt | xargs -I{} curl -s -o /dev/null -w "%{http_code}\\n" {}', 'echo 1 2 3 4 | xargs -n 2 echo'] },
    { command: 'tr [选项] SET1 [SET2]', category: '文本', params: '-d 删除字符; -s 压缩重复; -c 补集; -[:upper:] 字符类', description: '字符替换/压缩/删除', examples: ['echo "HELLO" | tr A-Z a-z', 'echo "a  b   c" | tr -s " "', 'cat file.txt | tr -d \'\\r\''] },
    { command: 'diff [选项] file1 file2', category: '文本', params: '-u unified 格式(推荐); -y 并排; -r 递归目录; -q 仅报告不同; -w 忽略空白', description: '比较两个文件/目录差异', examples: ['diff -u old.txt new.txt', 'diff -rq dir1/ dir2/', 'diff -y --suppress-common-lines a.txt b.txt'] },
    // === 压缩打包 ===
    { command: 'tar [选项] archive.tar 来源', category: '压缩', params: '-c 创建; -x 解压; -t 列表; -z gzip; -j bzip2; -J xz; -f 文件名(放最后); -v 详细; -C 切换目录', description: '归档工具（几乎是标配）', examples: ['tar -czvf backup.tar.gz /var/www', 'tar -xjf archive.tar.bz2 -C /tmp', 'tar -tzf backup.tar.gz | head -20'] },
    { command: 'gzip / gunzip [选项] 文件', category: '压缩', params: '-1~9 压缩率(9最高); -k 保留原文件; -d 解压; -l 列表', description: 'Gzip 压缩/解压', examples: ['gzip -9k data.csv', 'gunzip -k file.gz'] },
    { command: 'zip / unzip [选项] 压缩包 文件', category: '压缩', params: 'zip -r; unzip -l 列表; -o 覆盖; -P 密码; -d 解压目录', description: 'ZIP 压缩（跨平台）', examples: ['zip -r archive.zip src/', 'unzip -o archive.zip -d /tmp', 'zip -P secret backup.zip *.db'] },
    // === 系统 ===
    { command: 'top / free [-h]', category: '系统', params: 'free: -h 人类可读; -m MB; -s N 秒持续; -b buffer/cache 拆分', description: '查看内存使用', examples: ['free -h', 'free -h -s 2'] },
    { command: 'uptime', category: '系统', params: '-s 启动时间; -p 人类可读', description: '系统运行时长、负载', examples: ['uptime -p'] },
    { command: 'uname [选项]', category: '系统', params: '-a 全部; -r 内核版本; -m 架构; -o OS', description: '系统信息', examples: ['uname -a'] },
    { command: 'dmesg | tail -50', category: '系统', params: '-T 时间戳; -l 级别; -w 持续; -s 缓冲区大小', description: '内核日志（驱动/硬件问题排查）', examples: ['dmesg -T | tail -50', 'dmesg -l err -T'] },
    { command: 'journalctl [选项]', category: '系统', params: '-u service 服务日志; -f 实时; -n N 行数; --since "1 hour ago"; -p err 错误级别', description: 'systemd 日志查看', examples: ['journalctl -u nginx -f', 'journalctl --since "2 days ago" -p err', 'journalctl -u docker -n 200 --no-pager'] },
    { command: 'man 命令', category: '系统', params: '不带参打开手册; 1用户/2系统/3库/5配置文件; -k 关键词搜索', description: '查看命令手册页', examples: ['man 5 passwd', 'man -k socket'] },
    { command: 'history [-c]', category: '系统', params: '-c 清空; !n 执行历史第n条; !! 上一条; !$ 上一条最后参数; !cmd 执行最近cmd', description: 'Shell 历史命令', examples: ['history', '!42', 'sudo !!', 'cat !$'] },
    // === Vim/Vi 编辑器 ===
    { command: 'vim [文件]', category: 'vim', params: '-R 只读; -N 非兼容模式; +n 跳到第n行; +/pattern 打开即搜索', description: '进入 Vim 编辑器', examples: ['vim /etc/nginx/nginx.conf', 'vim +100 log.txt', 'vim -R /var/log/syslog'] },
    { command: '移动命令（普通模式）', category: 'vim', params: 'h/j/k/l 左下上右; 0 行首; $ 行尾; gg 首行; G 末行; nG 第n行; w/b/W/B 词间跳转; f/Fx 行内找x', description: '光标移动', examples: ['ggdG  全选删除（gog）', '120G  跳到第120行', 'f;  行内跳到下一个分号'] },
    { command: '进入插入模式', category: 'vim', params: 'i 前插入; a 后插入; I 行首; A 行尾; o 下一行; O 上一行; s 删1字符插; S 整行删插', description: '从普通模式进入编辑', examples: ['i  进入当前位置前插入', 'o  下面新开一行插入', 'ciw  删一个单词并插入（可重复：daw 删除单词不插入）'] },
    { command: '删除/复制/粘贴', category: 'vim', params: 'x 删1字符; dd 删1行; D 删到行尾; dw 删词; d5d 删5行; yy 复制行; yw 复制词; p/P 粘贴后/前; ddp 交换两行', description: '剪切板操作（vim 内部寄存器）', examples: ['dw  删一个词', '5yy  复制5行，然后 p 粘贴', '"+y  复制到系统剪贴板', 'ddp  把当前行和下一行交换'] },
    { command: '撤销/重做', category: 'vim', params: 'u 撤销; Ctrl+R 重做; . 重复上一条命令; :undo/:redo', description: '历史操作', examples: ['u  撤销', '.  重复刚才的 dww 等操作（超好用）'] },
    { command: '搜索/替换（行命令模式）', category: 'vim', params: '/pattern 向下搜; ?pattern 向上搜; n/N 下一/上一个; :s/旧/新/g 当前行替换; :%s/旧/新/g 全局; :n,ms/旧/新/g 范围', description: '搜索和替换', examples: ['/error  向下搜 error，n 下一个', ':%s/old/new/g  全文替换 old → new', ':1,10s/^/# /  1-10行注释加#'] },
    { command: '保存/退出（行命令模式 :）', category: 'vim', params: ':w 保存; :wq / :x 保存退出; :q! 放弃退出; :w file另存为; ZZ 保存退出(快捷键); ZQ 放弃退出', description: '文件操作', examples: [':w  保存', ':q!  不保存直接退出', 'ZZ  正常退出（比 :wq 更快）'] },
    { command: '可视模式 + 批量操作', category: 'vim', params: 'v 字符可视; V 行可视; Ctrl+v 块可视; 选中后 d 删/y 复制; :norm 批量执行; I/A 块插入/追加（块可视+I+输入+Esc）', description: '选中文本批量处理', examples: ['Ctrl+v 选多列 → I → # → Esc  批量加行注释', "选中多行 → :norm i// → Esc  每行开头加 //", '选中一段 → :w new.txt  另存为'] },
    { command: '多文件/标签/窗口', category: 'vim', params: ':e file 打开; :bn/:bp 下/上一buffer; :tabnew file 新标签; Ctrl+w s 水平分屏; Ctrl+w v 垂直分屏; Ctrl+w 方向 切换; :qa 全部退出', description: '多文件编辑', examples: [':tabnew config.js  新标签打开', 'Ctrl+w v  垂直分屏', ':qa  关闭所有'] },
    { command: '其他高频技巧', category: 'vim', params: '% 跳配对({[()]}); * 跳下一个相同单词; gd 跳定义; gf 打开光标下的文件; Ctrl+o/i 跳回/进（类似浏览器后退前进）; :cd 切换工作目录', description: '效率技巧', examples: ['gd  跳变量/函数定义（若有 tags）', '*  把光标下的单词自动搜一遍', 'Ctrl+o  回到上一次光标位置（编辑后常用）'] },
    // === SSH 远程操作 ===
    { command: 'ssh [选项] 用户@主机 [命令]', category: 'ssh', params: '-p 端口; -i 私钥文件; -X/-Y X11转发; -t 强制分配TTY; -o 选项(StrictHostKeyChecking=no); -F 指定config', description: '远程登录执行命令', examples: ['ssh root@192.168.1.10', 'ssh -p 2222 -i ~/.ssh/id_rsa admin@server', 'ssh root@server "ls -la /var/log"'] },
    { command: 'SSH 端口转发', category: 'ssh', params: '-L 本地转发: -L 本地端口:目标主机:目标端口; -R 远程转发; -D SOCKS代理: -D 1080', description: '隧道穿透', examples: ['ssh -L 8080:localhost:8080 root@server  本地8080→服务器8080', 'ssh -D 1080 root@server  开 SOCKS5 代理(浏览器走 localhost:1080)', 'ssh -L 3306:db-server:3306 root@server  借服务器连内网MySQL'] },
    { command: 'scp [选项] 源 目标', category: 'ssh', params: '-r 递归目录; -P 端口; -i 私钥; -p 保留时间属性; -l 限速KB/s; -o 选项', description: '文件传输（底层用ssh）', examples: ['scp -r ./dist user@server:/var/www/', 'scp -P 2222 key.pem root@server:/etc/', 'scp user@server:/var/log/nginx/error.log ./'] },
    { command: 'rsync [选项] 源 目标', category: 'ssh', params: '-a 归档(=rlptgoD); -v 详细; -p 进度; -z 压缩; -n dry-run; --delete 删除多余; --exclude="*.tmp"; -e ssh指定shell', description: '增量同步（比scp强得多）', examples: ['rsync -avz ./dist/ user@server:/var/www/app/', 'rsync -avz --delete ./ user@server:/backup/  镜像同步', 'rsync -avz --exclude="node_modules" ./ user@server:~/project/'] },
    { command: 'ssh-keygen [选项]', category: 'ssh', params: '-t ed25519|rsa|ecdsa; -b 位数; -f 文件路径; -C 注释; -N 空密码短语', description: '生成SSH密钥对', examples: ["ssh-keygen -t ed25519 -C 'lito@dev' -f ~/.ssh/id_ed25519", "ssh-keygen -t rsa -b 4096 -C 'deploy' -f ~/.ssh/deploy_key"] },
    { command: 'ssh-copy-id 用户@主机', category: 'ssh', params: '-i 公钥文件; -p 端口; -o ssh选项', description: '一键配置免密登录（把本地公钥追加到远程authorized_keys）', examples: ['ssh-copy-id root@192.168.1.10', 'ssh-copy-id -i ~/.ssh/id_ed25519.pub root@server'] },
    // === 进程后台/常驻 ===
    { command: 'nohup 命令 [&]', category: '后台', params: '输出默认追加 nohup.out; > out.log 2>&1 重定向; & 后台; 终端关闭不影响', description: '后台运行不挂断（已在进程管理出现，重复但常用）', examples: ['nohup python server.py > server.log 2>&1 &', 'nohup java -jar app.jar &', 'disown  # 将已后台任务脱离当前shell'] },
    { command: 'tmux [子命令]', category: '后台', params: 'new -s name 新会话; ls 列表; attach -t name 接入; kill-session -t name; send-keys; source-file', description: '终端多路复用（断线重连不丢任务）', examples: ['tmux new -s build', 'tmux ls', 'tmux attach -t build', 'Ctrl+b d  # detach 快捷键，会话仍在跑'] },
    { command: 'screen [选项]', category: '后台', params: '-S 会话名; -ls 列表; -r 恢复; -wipe 清理死会话', description: '另一款终端复用工具（比tmux老）', examples: ['screen -S dev', 'screen -ls', 'screen -r dev'] },
    // === 压缩打包补充 ===
    { command: '7z [子命令]', category: '压缩', params: 'a 添加; x 解压; l 列表; t 测试; e 解压到当前目录; b 基准测试; -p 密码; -mx 压缩率', description: '7-Zip 压缩（Linux 上需 p7zip）', examples: ['7z a archive.7z ./src', '7z x archive.7z -o./out', '7z l archive.7z'] },
    // === 其他高频遗漏 ===
    { command: 'chage [选项] 用户', category: '权限', params: '-l 列出密码过期信息; -d 设置最后修改日期; -E 账户过期日期; -M 最大密码存活天数; -m 最小天数; -W 警告提前天数', description: '修改用户密码过期策略', examples: ['chage -l lito', 'chage -E 2025-12-31 devuser', 'chage -M 90 -m 7 -W 14 root'] },
    { command: 'at / crontab', category: '系统', params: 'crontab -e 编辑; -l 列表; -r 清空; at now + 1 hour; atq 队列; atrm 删任务', description: '定时任务', examples: ['crontab -e', '0 2 * * * /usr/local/bin/backup.sh  # 每天凌晨2点', 'at 23:00 tomorrow', 'at 17:30 + 3 days <<< "systemctl restart nginx"'] },
    { command: 'tail -f / tail -F 对比', category: '文件', params: '-f 文件不重建继续追; -F 文件重建后自动重开; --retry 断开重试', description: '两种文件追踪模式差异', examples: ['tail -f log.txt  # 如果log.txt被重建(日志轮转)，会停止', 'tail -F log.txt  # 自动重新打开新文件，推荐看日志'] },
  ],
}
