import type { CheatSheetData } from './index'

export const mimeTypes: CheatSheetData = {
  id: 'mime',
  name: 'MIME 类型',
  description: '常见文件扩展名与 MIME 类型对照，点击扩展名或 MIME 可复制',
  columns: [
    { key: 'ext', label: '扩展名', width: '100px', copyable: true },
    { key: 'mime', label: 'MIME 类型', width: '220px', copyable: true },
    { key: 'category', label: '分类', width: '100px' },
    { key: 'description', label: '说明' },
  ],
  rows: [
    { ext: '.html', mime: 'text/html', category: '文本', description: 'HTML 文档' },
    { ext: '.htm', mime: 'text/html', category: '文本', description: 'HTML 文档' },
    { ext: '.css', mime: 'text/css', category: '文本', description: 'CSS 样式表' },
    { ext: '.js', mime: 'text/javascript', category: '文本', description: 'JavaScript 脚本' },
    { ext: '.json', mime: 'application/json', category: '应用', description: 'JSON 数据' },
    { ext: '.xml', mime: 'application/xml', category: '应用', description: 'XML 数据' },
    { ext: '.txt', mime: 'text/plain', category: '文本', description: '纯文本' },
    { ext: '.md', mime: 'text/markdown', category: '文本', description: 'Markdown 文档' },
    { ext: '.csv', mime: 'text/csv', category: '文本', description: 'CSV 表格' },
    { ext: '.yaml', mime: 'application/x-yaml', category: '应用', description: 'YAML 配置' },
    { ext: '.yml', mime: 'application/x-yaml', category: '应用', description: 'YAML 配置' },
    { ext: '.toml', mime: 'application/toml', category: '应用', description: 'TOML 配置' },
    { ext: '.pdf', mime: 'application/pdf', category: '应用', description: 'PDF 文档' },
    { ext: '.zip', mime: 'application/zip', category: '应用', description: 'ZIP 压缩包' },
    { ext: '.gz', mime: 'application/gzip', category: '应用', description: 'Gzip 压缩' },
    { ext: '.tar', mime: 'application/x-tar', category: '应用', description: 'TAR 归档' },
    { ext: '.7z', mime: 'application/x-7z-compressed', category: '应用', description: '7-Zip 压缩包' },
    { ext: '.rar', mime: 'application/x-rar-compressed', category: '应用', description: 'RAR 压缩包' },
    { ext: '.png', mime: 'image/png', category: '图片', description: 'PNG 图片' },
    { ext: '.jpg', mime: 'image/jpeg', category: '图片', description: 'JPEG 图片' },
    { ext: '.jpeg', mime: 'image/jpeg', category: '图片', description: 'JPEG 图片' },
    { ext: '.gif', mime: 'image/gif', category: '图片', description: 'GIF 动图' },
    { ext: '.svg', mime: 'image/svg+xml', category: '图片', description: 'SVG 矢量图' },
    { ext: '.webp', mime: 'image/webp', category: '图片', description: 'WebP 图片' },
    { ext: '.ico', mime: 'image/x-icon', category: '图片', description: '图标文件' },
    { ext: '.bmp', mime: 'image/bmp', category: '图片', description: 'BMP 位图' },
    { ext: '.avif', mime: 'image/avif', category: '图片', description: 'AVIF 图片' },
    { ext: '.mp3', mime: 'audio/mpeg', category: '音频', description: 'MP3 音频' },
    { ext: '.wav', mime: 'audio/wav', category: '音频', description: 'WAV 音频' },
    { ext: '.ogg', mime: 'audio/ogg', category: '音频', description: 'OGG 音频' },
    { ext: '.m4a', mime: 'audio/mp4', category: '音频', description: 'M4A 音频' },
    { ext: '.flac', mime: 'audio/flac', category: '音频', description: 'FLAC 无损音频' },
    { ext: '.mp4', mime: 'video/mp4', category: '视频', description: 'MP4 视频' },
    { ext: '.webm', mime: 'video/webm', category: '视频', description: 'WebM 视频' },
    { ext: '.avi', mime: 'video/x-msvideo', category: '视频', description: 'AVI 视频' },
    { ext: '.mov', mime: 'video/quicktime', category: '视频', description: 'QuickTime 视频' },
    { ext: '.mkv', mime: 'video/x-matroska', category: '视频', description: 'Matroska 视频' },
    { ext: '.woff', mime: 'font/woff', category: '字体', description: 'Web 字体' },
    { ext: '.woff2', mime: 'font/woff2', category: '字体', description: 'Web 字体 2.0' },
    { ext: '.ttf', mime: 'font/ttf', category: '字体', description: 'TrueType 字体' },
    { ext: '.otf', mime: 'font/otf', category: '字体', description: 'OpenType 字体' },
    { ext: '.eot', mime: 'application/vnd.ms-fontobject', category: '字体', description: '嵌入式字体' },
    { ext: '.sql', mime: 'application/sql', category: '应用', description: 'SQL 脚本' },
    { ext: '.sh', mime: 'application/x-sh', category: '应用', description: 'Shell 脚本' },
    { ext: '.bat', mime: 'application/x-msdownload', category: '应用', description: '批处理脚本' },
    { ext: '.exe', mime: 'application/octet-stream', category: '应用', description: '可执行文件' },
    { ext: '.wasm', mime: 'application/wasm', category: '应用', description: 'WebAssembly 二进制' },
    { ext: '.form', mime: 'application/x-www-form-urlencoded', category: '应用', description: '表单编码' },
    { ext: '.multipart', mime: 'multipart/form-data', category: '应用', description: '多部分表单' },
  ],
}
