import type { CheatSheetData } from './index'

export const sqlCheatsheet: CheatSheetData = {
  id: 'sql',
  name: 'SQL 常用语法',
  description: 'SELECT/WHERE/JOIN/GROUP BY/子查询/事务/索引等通用 SQL 语法速查（兼容 MySQL/PostgreSQL/SQLite）',
  columns: [
    { key: 'syntax', label: '语法', width: '260px', copyable: true },
    { key: 'category', label: '分类', width: '100px' },
    { key: 'params', label: '常用参数/变体', width: '220px' },
    { key: 'description', label: '说明' },
  ],
  rows: [
    // === 查询基础 ===
    { syntax: 'SELECT 列 FROM 表 WHERE 条件', category: '查询', params: 'DISTINCT 去重; * 所有列; AS 别名', description: '基础查询', examples: ['SELECT id, name FROM users WHERE id = 1', 'SELECT DISTINCT city FROM orders', 'SELECT u.name AS username FROM users u'] },
    { syntax: 'SELECT * FROM 表 ORDER BY 列 [ASC|DESC]', category: '查询', params: '多列用逗号; LIMIT N OFFSET M', description: '排序（默认ASC升序）', examples: ['SELECT * FROM products ORDER BY price DESC', 'SELECT * FROM logs ORDER BY created_at DESC LIMIT 20 OFFSET 40'] },
    { syntax: 'SELECT * FROM 表 LIMIT N OFFSET M', category: '查询', params: 'MySQL: LIMIT M,N; PostgreSQL: LIMIT N OFFSET M; SQL Server: OFFSET M ROWS FETCH NEXT N ROWS ONLY', description: '分页查询', examples: ['SELECT * FROM users ORDER BY id LIMIT 10 OFFSET 20', '-- SQL Server 写法\nSELECT * FROM users ORDER BY id OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY'] },
    { syntax: 'WHERE 条件组合', category: '查询', params: '= <> != > < >= <=; AND/OR/NOT; IN/NOT IN; BETWEEN; LIKE; IS NULL; ALL/ANY/SOME; EXISTS', description: '条件表达式', examples: ["WHERE status = 'active' AND age >= 18", 'WHERE country IN ("CN", "US", "JP")', 'WHERE price BETWEEN 100 AND 200', "WHERE name LIKE '%张%' AND city IS NOT NULL"] },
    { syntax: 'LIKE 通配符匹配', category: '查询', params: '% 任意字符; _ 单字符; ESCAPE \'x\' 指定转义; ILIKE(PG) 大小写不敏感', description: '模糊搜索', examples: ["SELECT * FROM users WHERE name LIKE 'A%'", "SELECT * FROM users WHERE email LIKE '%@gmail.com'", "-- 搜索包含 % 的文本\nSELECT * FROM logs WHERE msg LIKE '%\\%%' ESCAPE '\\'"] },
    // === 聚合函数 ===
    { syntax: 'COUNT(* | COUNT(列) | COUNT(DISTINCT 列)', category: '聚合', params: 'COUNT(*) 全部行数; COUNT(列) 非NULL行数; COUNT(DISTINCT col) 去重计数', description: '计数', examples: ['SELECT COUNT(*) FROM users', 'SELECT COUNT(DISTINCT country) FROM orders', 'SELECT COUNT(*) - COUNT(email) AS no_email FROM users'] },
    { syntax: 'SUM / AVG / MAX / MIN(列)', category: '聚合', params: 'MAX(price); AVG(score); 可配合 CAST', description: '数值聚合', examples: ['SELECT SUM(total) AS revenue, AVG(total) AS avg_order FROM orders WHERE status="paid"', 'SELECT MAX(created_at) FROM users'] },
    { syntax: 'GROUP BY 列 [HAVING 条件]', category: '聚合', params: 'HAVING 过滤分组后结果(WHERE过滤前); ROLLUP 生成小计/总计; CUBE 全维度组合', description: '分组统计', examples: ['SELECT country, COUNT(*) FROM users GROUP BY country', 'SELECT dept, AVG(salary) FROM emp GROUP BY dept HAVING AVG(salary) > 5000', "-- ROLLUP 生成小计\nSELECT dept, SUM(salary) FROM emp GROUP BY ROLLUP(dept)"] },
    // === JOIN ===
    { syntax: 'INNER JOIN 表 ON 条件', category: '连接', params: 'INNER 可省略; USING(列) 简化同名列条件; ON vs WHERE 不同', description: '内连接（两表匹配才出）', examples: ["SELECT u.name, o.total FROM users u JOIN orders o ON u.id = o.user_id AND o.status = 'paid'"] },
    { syntax: 'LEFT / RIGHT / FULL OUTER JOIN 表 ON 条件', category: '连接', params: 'LEFT 保留左表全量; RIGHT 保留右表全量; FULL 两表全量; OUTER 可省略', description: '外连接', examples: ['SELECT u.name, o.total FROM users u LEFT JOIN orders o ON u.id = o.user_id', '-- 找没有订单的用户\nSELECT u.name FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE o.id IS NULL'] },
    { syntax: 'CROSS JOIN 表', category: '连接', params: '等价于 FROM A, B (笛卡尔积)', description: '交叉连接（笛卡尔积）', examples: ['SELECT * FROM product CROSS JOIN color', '-- 生成所有组合\nSELECT A.course, B.room FROM courses A CROSS JOIN rooms B'] },
    { syntax: '自连接', category: '连接', params: '同表起不同别名', description: '表自身与自身连接（组织结构）', examples: ['SELECT e.name, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id'] },
    // === 子查询 ===
    { syntax: 'WHERE col IN (SELECT col FROM ...)', category: '子查询', params: 'IN / = / ANY / ALL / EXISTS 运算符', description: '标量/列子查询', examples: ["SELECT * FROM users WHERE id IN (SELECT user_id FROM orders WHERE status = 'paid')", "-- EXISTS 版\nSELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.status = 'paid')"] },
    { syntax: 'FROM (SELECT ...) AS 别名', category: '子查询', params: '派生表/内联视图', description: 'FROM 子句中嵌套查询', examples: ['SELECT * FROM (SELECT user_id, COUNT(*) AS cnt FROM orders GROUP BY user_id) AS t WHERE t.cnt > 3'] },
    { syntax: 'SELECT col, (SELECT ...) AS alias', category: '子查询', params: '相关子查询（引用外层表）', description: '标量子查询（每行执行一次）', examples: ["SELECT u.*, (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) AS order_cnt FROM users u"] },
    { syntax: 'WITH CTE AS (SELECT ...) SELECT ...', category: '子查询', params: '递归CTE(含 UNION ALL); 多个CTE用逗号', description: '公用表表达式（CTE / WITH）', examples: ['WITH active_users AS (SELECT * FROM users WHERE status = "active")\nSELECT au.name, o.total FROM active_users au JOIN orders o ON au.id = o.user_id', '-- 递归CTE找层级\nWITH RECURSIVE org AS (SELECT * FROM dept WHERE id = 1 UNION ALL SELECT d.* FROM dept d JOIN org ON d.parent_id = org.id) SELECT * FROM org'] },
    // === 集合运算 ===
    { syntax: '(SELECT ...) UNION [ALL] (SELECT ...)', category: '集合', params: 'UNION 去重; UNION ALL 保留全部(快); 两SELECT列数/类型必须一致', description: '集合合并', examples: ['(SELECT name AS item FROM products) UNION ALL (SELECT title AS item FROM posts)'] },
    { syntax: 'INTERSECT / EXCEPT (SELECT ...)', category: '集合', params: 'INTERSECT 交集; EXCEPT/MINUS 差集; MySQL 无 INTERSECT', description: '集合交/差', examples: ['-- 既买了A又买了B的用户\n(SELECT user_id FROM orders WHERE product_id = 1) INTERSECT (SELECT user_id FROM orders WHERE product_id = 2)', '-- PG/MariaDB\n(SELECT user_id FROM orders) EXCEPT (SELECT user_id FROM refunds)'] },
    // === 增删改 ===
    { syntax: 'INSERT INTO 表 [(列1,列2)] VALUES (v1,v2), (...)', category: '增删改', params: '批量多行; RETURNING(PG/SQLite)返回插入行', description: '插入数据', examples: ["INSERT INTO users (name, email) VALUES ('Alice', 'a@x.com'), ('Bob', 'b@x.com')", "-- PostgreSQL 返回自增ID\nINSERT INTO users (name) VALUES ('X') RETURNING id"] },
    { syntax: 'INSERT INTO 表 SELECT ...', category: '增删改', params: '从查询结果插入', description: '从其他表复制数据', examples: ['INSERT INTO archive SELECT * FROM orders WHERE created_at < "2024-01-01"'] },
    { syntax: 'INSERT ... ON DUPLICATE KEY UPDATE / ON CONFLICT DO UPDATE', category: '增删改', params: 'MySQL: ON DUPLICATE KEY; PG/SQLite: ON CONFLICT(列) DO UPDATE/NOTHING', description: '冲突更新/Upsert', examples: ["INSERT INTO kv (k, v) VALUES ('a', 1) ON DUPLICATE KEY UPDATE v = v + 1", "-- PostgreSQL\nINSERT INTO kv (k, v) VALUES ('a', 1) ON CONFLICT(k) DO UPDATE SET v = EXCLUDED.v", "-- SQLite\nINSERT INTO kv (k, v) VALUES ('a', 1) ON CONFLICT(k) DO NOTHING"] },
    { syntax: 'UPDATE 表 SET 列=值 [,列2=值2] WHERE 条件', category: '增删改', params: '多表JOIN更新(MySQL: UPDATE t1 JOIN t2 ...); LIMIT; ORDER BY', description: '更新数据（务必加WHERE！）', examples: ["UPDATE users SET status = 'verified' WHERE email_verified = 1", "-- MySQL 多表更新\nUPDATE orders o JOIN users u ON o.user_id = u.id SET o.priority = 1 WHERE u.vip = 1"] },
    { syntax: 'DELETE FROM 表 WHERE 条件', category: '增删改', params: '务必加WHERE！; TRUNCATE 清空表(不可回滚); DELETE 逐行可回滚; 多表删', description: '删除数据', examples: ['DELETE FROM logs WHERE created_at < "2024-01-01"', 'TRUNCATE TABLE logs', "-- MySQL 多表删除\nDELETE o FROM orders o LEFT JOIN users u ON o.user_id = u.id WHERE u.id IS NULL"] },
    { syntax: 'MERGE INTO 目标 USING 源 ON 条件 WHEN MATCHED THEN ...', category: '增删改', params: 'MERGE = UPSERT 的完整版; MySQL 8+ 用 INSERT ON DUPLICATE KEY', description: '合并插入/更新（Oracle/SQL Server）', examples: ["-- PostgreSQL 使用 INSERT ON CONFLICT 代替 MERGE"] },
    // === 表结构 ===
    { syntax: 'CREATE TABLE 表 (列 类型 [约束], ...)', category: 'DDL', params: 'PRIMARY KEY(col); UNIQUE(col); NOT NULL; DEFAULT val; FOREIGN KEY REFERENCES', description: '创建表', examples: ['CREATE TABLE users (\n  id BIGSERIAL PRIMARY KEY,\n  name VARCHAR(50) NOT NULL,\n  email VARCHAR(100) UNIQUE,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n)', 'CREATE TABLE orders (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  user_id INT NOT NULL,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n)'] },
    { syntax: 'ALTER TABLE 表 [操作]', category: 'DDL', params: 'ADD COLUMN; DROP COLUMN; ALTER COLUMN; RENAME TO; RENAME COLUMN; ADD CONSTRAINT', description: '修改表结构', examples: ['ALTER TABLE users ADD COLUMN phone VARCHAR(20)', 'ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(150)', 'ALTER TABLE users RENAME TO accounts'] },
    { syntax: 'DROP / TRUNCATE / RENAME TABLE', category: 'DDL', params: 'DROP 删表结构+数据; TRUNCATE 删数据保留结构; RENAME 改名', description: '删除/清空/重命名表', examples: ['DROP TABLE IF EXISTS old_table', 'TRUNCATE TABLE temp_queue', '-- MySQL\nRENAME TABLE users TO accounts', '-- PostgreSQL\nALTER TABLE users RENAME TO accounts'] },
    // === 索引 ===
    { syntax: 'CREATE [UNIQUE] INDEX 名 ON 表 (列[,列]...)', category: '索引', params: 'UNIQUE 唯一索引; (col,col) 复合索引; 表达式索引 PG: (LOWER(email))', description: '创建索引', examples: ['CREATE INDEX idx_users_email ON users(email)', 'CREATE UNIQUE INDEX uk_users_email ON users(email)', '-- PostgreSQL 表达式索引\nCREATE INDEX idx_posts_title ON posts(LOWER(title))'] },
    { syntax: 'CREATE INDEX ... CONCURRENTLY [WHERE 条件]', category: '索引', params: 'PostgreSQL 特有; CONCURRENTLY 不锁表; WHERE 部分索引', description: '在线创建/部分索引（PG）', examples: ["CREATE INDEX CONCURRENTLY idx_orders_paid ON orders(status) WHERE status = 'paid'", '-- 最左前缀原则：(a,b,c) 能加速 a / a,b / a,b,c，不能加速 b 或 c 或 b,c'] },
    { syntax: 'DROP INDEX 名', category: '索引', params: 'DROP INDEX CONCURRENTLY 名(PG 锁表)', description: '删除索引', examples: ['DROP INDEX IF EXISTS idx_users_email', 'DROP INDEX CONCURRENTLY idx_old_index'] },
    { syntax: 'EXPLAIN [ANALYZE] 查询', category: '索引', params: 'ANALYZE 实际执行; VERBOSE 详细; 可视化工具 pgAdmin EXPLAIN; MySQL EXPLAIN 类型列看索引是否命中', description: '执行计划分析（调优必备）', examples: ['EXPLAIN SELECT * FROM users WHERE email = "a@x.com"', 'EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 1 ORDER BY created_at DESC'] },
    // === 事务 ===
    { syntax: 'BEGIN / START TRANSACTION', category: '事务', params: 'BEGIN WORK; SET TRANSACTION ISOLATION LEVEL READ COMMITTED', description: '开启事务', examples: ['BEGIN;', 'BEGIN; SET TRANSACTION ISOLATION LEVEL SERIALIZABLE'] },
    { syntax: 'COMMIT / ROLLBACK / SAVEPOINT', category: '事务', params: 'SAVEPOINT sp; ROLLBACK TO sp; RELEASE SAVEPOINT', description: '提交/回滚/保存点', examples: ['BEGIN; INSERT INTO t VALUES(1); COMMIT;', "BEGIN; SAVEPOINT sp1; INSERT INTO t VALUES(1); ROLLBACK TO sp1; COMMIT;"] },
    { syntax: 'SELECT ... FOR UPDATE [OF 表]', category: '事务', params: 'SKIP LOCKED; NO WAIT; PG: FOR UPDATE OF t; MySQL: 行锁', description: '悲观锁（防止并发修改）', examples: ['BEGIN; SELECT balance FROM accounts WHERE id = 1 FOR UPDATE; UPDATE accounts SET balance = balance - 100 WHERE id = 1; COMMIT;', '-- 跳过已锁行（PG）\nSELECT * FROM queue FOR UPDATE SKIP LOCKED LIMIT 10'] },
    // === 窗口函数 ===
    { syntax: 'ROW_NUMBER() OVER (PARTITION BY col ORDER BY col)', category: '窗口', params: 'ROW_NUMBER() 序号; RANK() 排名(并列跳过); DENSE_RANK() 排名(不跳过); LAG/LEAD; SUM/AVG OVER(PARTITION BY)', description: '窗口函数（8.0+/PG 8.4+）', examples: ['-- 每部门按工资排序\nSELECT dept, name, salary, ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC) AS rn FROM emp', '-- 累计求和\nSELECT date, amount, SUM(amount) OVER(ORDER BY date) AS running_total FROM sales', '-- 上一行/下一行\nSELECT *, LAG(price) OVER(ORDER BY date) AS prev FROM stock_prices'] },
    // === 常用函数 ===
    { syntax: '字符串函数', category: '函数', params: 'CONCAT; SUBSTRING/LSUBSTR; TRIM/LTRIM/RTRIM; UPPER/LOWER; REPLACE; LENGTH/CHAR_LENGTH; POSITION(PG)/INSTR(MySQL); LEFT/RIGHT', description: '字符串操作', examples: ["SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM users", "SELECT SUBSTRING(title, 1, 50) AS preview FROM posts", "-- MySQL INSTR, PostgreSQL POSITION\nSELECT name FROM users WHERE INSTR(email, '@gmail.com') > 0"] },
    { syntax: '日期/时间函数', category: '函数', params: 'NOW()/CURRENT_TIMESTAMP; DATE/EXTRACT/DATE_TRUNC(PG); DATE_FORMAT(MySQL)/TO_CHAR(PG); DATE_ADD/DATE_SUB(MySQL); INTERVAL', description: '日期操作', examples: ["SELECT NOW(), CURDATE()", "-- PostgreSQL\nSELECT NOW() - INTERVAL '7 days'", "-- MySQL\nSELECT NOW() - INTERVAL 7 DAY", "-- 每月第一天\nSELECT DATE_TRUNC('month', NOW())", "-- 格式化\nSELECT TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI:SS')  -- PG\nSELECT DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s')  -- MySQL"] },
    { syntax: 'CASE WHEN 条件 THEN 值 [ELSE 值] END', category: '函数', params: '简单CASE: CASE col WHEN x THEN v; 搜索CASE: CASE WHEN cond THEN v', description: '条件表达式（替代 if/else）', examples: ["SELECT name,\n  CASE WHEN score >= 90 THEN 'A'\n       WHEN score >= 80 THEN 'B'\n       ELSE 'C' END AS grade\nFROM students"] },
    { syntax: 'COALESCE / NULLIF / CAST', category: '函数', params: 'COALESCE(a,b,c) 首个非NULL; NULLIF(a,b) 相等返回NULL; CAST(x AS type)', description: 'NULL 处理/类型转换', examples: ["SELECT name, COALESCE(nickname, name) AS display_name FROM users", "SELECT CAST(price AS DECIMAL(10,2)) FROM products", "SELECT NULLIF(a, 0) AS safe_div FROM data"] },
  ],
}
