// Auto-generated by scripts/gen-changelog.cjs
// 请勿手动修改此文件，如需更新请运行: node scripts/gen-changelog.cjs

export interface ChangelogEntry {
  version: string
  date: string
  content: string
  isEnhancement: boolean
  isNewFeature: boolean
}

export interface ChangelogData {
  versionRange: string
  entries: ChangelogEntry[]
}

export const changelogData: ChangelogData = {
  versionRange: "从 v1.0 到 v8.0.1 更新内容",
  entries: [
  {
    "version": "8.0.1",
    "date": "2026-08-16",
    "content": "窗口体验优化：默认窗口尺寸从 1300×850 调小为 1100×720，适配 13/15 寸小屏笔记本；修复窗口尺寸记忆失效问题（统一使用 innerSize/innerPosition 替代 outerSize，避免\"保存外部尺寸→恢复内部尺寸\"导致的尺寸漂移）；新增最大化状态记忆；窗口拖动/缩放事件加 300ms 防抖，避免频繁写 localStorage",
    "isEnhancement": true,
    "isNewFeature": true
  },
  {
    "version": "8.0.0",
    "date": "2026-08-13",
    "content": "图片 EXIF 工具：选择/拖拽图片即时读取 EXIF 信息（相机品牌型号、镜头、拍摄时间、光圈/快门/ISO/焦距、曝光补偿、白平衡、闪光灯、作者/版权/软件/图片描述等隐私字段），GPS 定位高亮展示（度分秒 + 十进制坐标一键复制），支持 JPEG/TIFF/PNG/WebP 等格式；一键清除隐私元数据——JPEG 无损剥离 EXIF/XMP/IPTC/注释段（不重编码不损失画质），PNG/WebP 通过 Canvas 重绘剥离，剥离后对比展示文件大小；基于 exifr 纯前端实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.19.0",
    "date": "2026-08-13",
    "content": "OpenAPI 解析工具：解析 OpenAPI 3.x / Swagger 2.0 文档（JSON/YAML），接口清单按标签分组过滤展示（方法彩色徽标/路径/摘要/弃用标记），展开查看参数表（名称/位置/类型/必填/描述）、请求体、各状态码响应 Schema 与媒体类型；每个接口一键生成 curl / fetch 请求示例（路径/查询/Header 参数自动填充示例值、请求体自动 Mock）、响应 Mock 数据、响应 TS 类型；支持导出全量接口清单 JSON 与全部命名 Schema 的 TS 类型，Base URL 自定义，粘贴自动解析（300ms 防抖），工作流可调用（输出接口清单 JSON）；基于 js-yaml + json-schema-faker 纯前端实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.18.0",
    "date": "2026-08-12",
    "content": "番茄钟工具：专注+休息循环（25/5/15 分钟默认，专注/短休/长休时长与长休间隔均可自定义）、Rust 后端秒级计时状态机（主窗口最小化/遮挡不影响计时，到点自动切换下一阶段）、到点双重提醒（蜂鸣声 + Windows 系统通知）、全局快捷键 Ctrl+Alt+Shift+P 一键开始/暂停（可在快捷键设置中修改）；基于 tauri-plugin-notification 系统通知实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.17.0",
    "date": "2026-08-12",
    "content": "Mermaid 图表渲染工具：输入 Mermaid 语法实时渲染预览（300ms 防抖），内置 10 种常用模板一键插入（流程图/时序图/类图/状态图/ER图/甘特图/饼图/思维导图/用户旅程/Git图），12 种主题切换（跟随应用/经典/森林/中性/新潮/新潮暗色/暗色/基础/Redux系列）与字号调节、预览缩放与背景模式（跟随主题/白色/透明棋盘格）、导出 SVG / PNG（2x 高清栅格化、PNG 背景跟随所选模式、大图自动限幅）、模板 classDef 美化配色、渲染失败定位错误信息，工作流可调用（输入源码输出 SVG）；基于 mermaid 库纯前端实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.16.0",
    "date": "2026-08-12",
    "content": "压缩/解压工具：多文件/文件夹 ZIP 打包（压缩级别存储/最快/默认/最大可调）、ZIP 内容预览列表（名称/类型/原始大小/压缩后大小/修改时间）与勾选部分条目解压、密码加密压缩（ZipCrypto 兼容 Windows/7-Zip/WinRAR）与密码解密（支持 AES-256 加密包）、防路径穿越（Zip Slip）、实时进度事件（当前文件+百分比）；后端基于 zip crate 纯 Rust 实现，目录递归收集、UTF-8 文件名、跳过已存在/不安全路径统计",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "7.15.0",
    "date": "2026-08-11",
    "content": "~~文件占用检测~~ 已放弃：曾实现 PowerToys FileLocksmith 同款句柄枚举方案（NtQuerySystemInformation + NtDuplicateObject + GetFinalPathNameByHandleW），因 Windows API 环境兼容性问题无法可靠检测占用进程——Restart Manager（RmRegisterResources）在部分机器上内部挂起导致检测卡死，句柄枚举受 SeDebugPrivilege 与系统环境限制不稳定；**以后不再实现文件占用检测功能**",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "7.14.2",
    "date": "2026-08-11",
    "content": "搜索键盘导航：首页搜索工具下拉列表支持 ↑↓ 方向键选择（高亮+自动滚动）、Enter 跳转、Esc 清空；全文搜索工具结果表格支持 ↑↓ 选择行、Enter 在资源管理器中定位；命令面板与快速启动弹窗确认支持 ↑↓/Enter/Esc，全程无需鼠标",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "7.14.1",
    "date": "2026-08-11",
    "content": "媒体信息工具优化：支持选择图片文件（JPG/PNG/WebP/GIF/BMP/TIFF/AVIF/ICO）与所有文件类型（默认选中），图片直接展示原图预览（点击放大）；视频流卡片适配图像流展示（帧率/时长/比特率为 0 时自动隐藏），增补图片编解码器（PNG/MJPEG/WebP/BMP/TIFF）、像素格式（BGR/BGRA/Pal8）、格式名称中文翻译",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "7.14.0",
    "date": "2026-08-11",
    "content": "本地静态服务器：一键启动 HTTP 静态文件服务，选择目录即起服务，自动展示本机 + 局域网访问地址（端口占用自动 +1 避让，可手动指定）；内建目录浏览页（上级导航/子目录/文件大小/修改时间，中文路径友好），文件点击内联打开或强制下载，子目录一键打包 ZIP 下载，网页端上传文件到当前目录（手机/局域网设备可直接传文件到电脑），实时访问日志（时间/IP/方法/路径/状态码）；后端基于 Rust 手写轻量 HTTP/1.1 服务，零新增依赖，支持 keep-alive、CORS、路径穿越防护、MIME 识别、GBK/中文文件名 URL 编码",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "7.13.0",
    "date": "2026-08-11",
    "content": "代码格式化工具（基于 Prettier 的多语言格式化：JS/TS/JSON/JSON5/CSS/SCSS/HTML/Vue/Markdown/YAML，缩进/分号/引号可调，插件按需懒加载，工作流可调用）+ 批量替换工具（多文件内容搜索替换，正则模式，UTF-8/GBK 编码自动保留，替换前自动备份到 .litobox_backup 目录）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.12.0",
    "date": "2026-08-10",
    "content": "图片对比：两张图片像素级对比，三种模式——滑动对比（拖动分割线左右查看）、差异高亮（红色标记差异像素，容差 0-128 可调，实时差异率统计）、半透明叠加（B 图透明度可调），自动统一尺寸对齐，大图等比降采样保证性能",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "7.11.0",
    "date": "2026-08-10",
    "content": "Git 仓库统计：选择本地 Git 仓库目录，统计总提交数/新增删除行数/贡献者数，贡献者排行（提交数进度条）、每日提交趋势图（30/90/365天/全部切换，SVG 柱状图悬停看明细）、文件改动 Top 10，基于系统 git 命令解析，异步后台分析不卡界面",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "7.10.0",
    "date": "2026-08-10",
    "content": "模板渲染工具：Handlebars 模板实时渲染（300ms 防抖），左侧模板/右侧 JSON 数据双栏编辑，实时开关，渲染预览 / HTML 源码两种视图切换，快捷插入常用语法片段（变量/#each/#if/条件逻辑），模板或数据解析错误实时提示，内置示例模板与示例数据",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.9.0",
    "date": "2026-08-10",
    "content": "JSON Schema 工具：draft-07 Schema 数据校验（错误路径/关键字/消息逐条展示）、依据 Schema 一键生成 Mock 测试数据（支持可选字段/默认值选项）、导出 TypeScript 接口定义，内置示例 Schema 与示例数据，基于 ajv + json-schema-faker 纯前端实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.8.0",
    "date": "2026-08-10",
    "content": "Excel 处理工具：读取 .xlsx/.xls/.csv 多 Sheet 浏览与切换、多文件合并（纵向追加行 / 横向拼接列）、数据清洗（去空行 / 按行去重 / 修剪空格 / 空值填充）、导出 CSV / JSON / Markdown / SQL INSERT，或另存为 .xlsx，数据预览开关（前100行 / 全部），基于 SheetJS 纯前端实现",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.7.0",
    "date": "2026-08-10",
    "content": "剪贴板格式转换工具：一键读取剪贴板内容并自动识别类型，剪贴板图片 ↔ Base64（DataURL）互转、HTML富文本 → Markdown 纯文本、表格（HTML table / TSV）→ Markdown / CSV / JSON / TSV 四种格式互转，彩色分组卡片样式，全部纯前端实现零额外依赖",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.6.0",
    "date": "2026-08-10",
    "content": "XML/YAML工具新增\"配置互转\"Tab：JSON / YAML / TOML / INI / Java Properties 5 种配置格式环形互转（统一中间层：源格式 → JS对象 → 目标格式），一键交换源↔目标格式（同时互换输入输出），选择格式时显示对应示例，INI 支持 section / 引号字符串 / 注释，Properties 支持点号键→嵌套对象 / \\n\\t 转义，手写 INI/Properties 解析器零额外依赖，仅 TOML 引入 @iarna/toml",
    "isEnhancement": true,
    "isNewFeature": true
  },
  {
    "version": "7.5.0",
    "date": "2026-08-10",
    "content": "拼音工具：中文转拼音，5 种输出模式（全拼带声调/全拼无声调/首字母大写/驼峰式/全小写无间隔），可调分隔符（空格/无/下划线/短横线），多音字候选展示（开启后列出所有多音字的所有读音），批量逐行处理，实时转换，历史记录还原",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.4.0",
    "date": "2026-08-10",
    "content": "条形码生成工具：支持 CODE128/EAN-13/EAN-8/UPC-A/CODE39/ITF-14/Codabar/MSI/Pharmacode 9 种一维条码格式，可调条宽/条高/边距/前景色/背景色/显示文字/字号，批量生成（每行一条，CSV/TXT 导入，ZIP 打包下载，序号/文本命名），格式切换自动提示输入要求，历史记录还原",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.3.0",
    "date": "2026-08-10",
    "content": "IP 子网计算器：IPv4 子网计算（网络地址/广播/掩码/反掩码/首末主机/主机数/IP类别/私网判断/二进制可视化，网络位与主机位分色高亮）、子网划分（按子网数量或每子网主机数，表格列出所有子网）、IP范围合并（起止IP转最少CIDR块列表）、IP↔整数互转（含十六进制/二进制），CIDR 与点分掩码两种输入格式，历史记录还原",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.2.0",
    "date": "2026-08-09",
    "content": "更新日志页面：读取 dev 分支所有 git 提交记录自动生成版本更新列表，按版本号时间线展示，支持按类型筛选（新增/修复/优化等）、关键词搜索、统计概览，提交详情按类型分组展示；侧边栏底部添加入口按钮（紫蓝渐变高亮 + 光泽动画）",
    "isEnhancement": true,
    "isNewFeature": true
  },
  {
    "version": "7.1.4",
    "date": "2026-08-09",
    "content": "PDF 加水印：支持文字/图片水印，9 宫格定位或平铺模式，可调节透明度、旋转角度、偏移量、字号/字体/颜色（文字）或图片尺寸（图片），纯前端 pdf-lib 实现，零额外依赖",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.1.3",
    "date": "2026-08-08",
    "content": "PDF 图片提取修复：修复 Vite 打包后 pdf-lib 类名带后缀（PDFRawStream2）导致 isStreamObj 判断失败、PDFName 访问方式从函数变为属性导致 resolvePdfName 返回空、dict.get 用字符串匹配 PDFName 对象失败的问题，兼容浏览器打包环境下的 pdf-lib 内部 API 变化",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "7.1.2",
    "date": "2026-08-08",
    "content": "PDF工具新增 Tab「提取图片」：从 PDF 中提取原始内嵌 XObject 位图资源（与「PDF 转图片」整页栅格化互为补充），自动去重跨页复用图片，支持 JPEG/DCTDecode 原生字节保存、FlateDecode 压缩位图用浏览器 DecompressionStream 解压后经 Canvas 重编码为 PNG（支持 RGB/Gray/CMYK 颜色空间转换），JPX/CCITT Fax/Raw 等罕见格式附带 SVG 占位预览并保存原始 bytes；卡片网格预览+格式彩色标签，单张保存+批量 ZIP 打包（含 UTF-8 BOM 的 _manifest.csv 清单文件记录页码/尺寸/颜色空间/过滤器等元数据）",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "7.1.1",
    "date": "2026-08-08",
    "content": "密码保管箱：无操作自动锁定功能（默认关闭，可在设置中开启；锁定时长可选 1/3/5/10/15/30 分钟，默认 5 分钟），头部实时显示剩余倒计时徽章，全局活动检测，配置持久化到 SQLite，重置主密码后配置自动恢复默认",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "7.1",
    "date": "2026-08-07",
    "content": "编码工具→编码转换（新增 HTML实体/Unicode 编解码、时间戳转换、输出转输入、彩色分组卡片样式）、哈希计算→加密解密（整合 AES/DES/3DES/RC4/Rabbit 对称加密、哈希算法扩展至 8 种：MD5/SHA-1/SHA-224/SHA-256/SHA-384/SHA-512/SHA-3/RIPEMD-160、算法说明 tooltip、Tab 切换哈希/加密）",
    "isEnhancement": true,
    "isNewFeature": true
  },
  {
    "version": "7.0",
    "date": "2026-08-07",
    "content": "侧边栏折叠菜单（可折叠/展开，折叠状态仅图标+原生 tooltip，状态持久化，0.25s 过渡动画）、侧边栏底部组件 tooltip 统一朝右、主题切换暗色模式修复、JSON 工具增强（数据统计：数组长度/对象属性数/嵌套总数，Key 筛选：深度搜索多匹配，布局优化：输入框缩小/操作+缩进合并/统计移到输出下方/筛选整合到输出标题栏）",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "6.14",
    "date": "2026-08-07",
    "content": "二维码美化：容错率可选（L/M/Q/H）、码点样式（方块/圆点/圆角）、渐变着色（亮度约束保证识别）、内嵌 Logo（大小按容错率自动约束）、自动验证（jsQR 解码校验）、智能风险提示（仅验证失败时高亮）、剪贴板读取 + Ctrl+V 粘贴解码",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.13",
    "date": "2026-08-07",
    "content": "二维码批量生成：每行一条文本/CSV 导入，批量生成多尺寸二维码，网格预览，ZIP 打包下载或单个下载/复制剪贴板，支持序号/文本内容命名",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.12",
    "date": "2026-08-07",
    "content": "SVG 工具：SVG 实时预览（透明棋盘格背景切换）、优化压缩（移除注释/metadata/空白）、转 PNG 栅格化（自定义尺寸/背景/保持比例/下载剪贴板）",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "6.11",
    "date": "2026-08-07",
    "content": "剪贴板历史增强：自动捕获文本/图片/文件路径三种类型，统一列表 + 类型筛选标签，图片缩略图预览 + 大图查看，文件路径一键复制，图片缓存本地临时文件 + DB 索引",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "6.10",
    "date": "2026-08-04",
    "content": "视频加水印：文字/图片/两者叠加水印，9 宫格位置 + 自定义偏移，可选限定时间段，仅 ffmpeg 模式可用",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.9",
    "date": "2026-07-29",
    "content": "快速启动：SQLite FTS5 全盘文件名索引，即时搜索，一键打开文件/目录（Alt+Space 呼出）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.8",
    "date": "2026-07-29",
    "content": "文件批量重命名：替换/正则/前后缀/序号四种模式，实时预览确认，冲突检测，一键执行，撤销恢复",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.7",
    "date": "2026-07-28",
    "content": "密码保管箱：主密码保护（SHA-256 加密）、凭据增删改查/搜索筛选、密码一键复制、批量导入（Edge/Chrome CSV 自动去重）、批量删除、修改主密码（重加密所有凭据）、重置找回",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.6",
    "date": "2026-07-27",
    "content": "证书查看器：查看 Windows 证书存储（个人/根/CA），解析 .cer/.crt/.pfx 文件，查看 SSL 证书详情（主题/颁发者/有效期/SAN/指纹）",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "6.5",
    "date": "2026-07-26",
    "content": "一键加速：内存释放（EmptyWorkingSet）+ 临时文件清理 + 回收站清空，一键扫描执行，显示释放量",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "6.4",
    "date": "2026-07-26",
    "content": "环境变量编辑器：查看/新增/修改/删除用户级和系统级环境变量，PATH 逐行列表编辑，表格行内编辑，CSV 导出，操作历史记录",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "6.3",
    "date": "2026-07-25",
    "content": "开机启动项管理：查看 Windows 开机启动项（注册表 Run 键 + 启动文件夹），来源/状态筛选，启用/禁用（重命名前缀法）/删除（二次确认）/新增（HKCU 注册表或用户启动文件夹），CSV 导出，操作历史记录",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "6.2",
    "date": "2026-07-24",
    "content": "计划任务管理器：查看 Windows 计划任务列表（默认隐藏 \\Microsoft\\Windows\\ 系统任务，开关控制展开），状态/搜索筛选，启用/禁用/立即运行/删除（系统任务禁删、danger 二次确认），触发器简述 + 展开行详情（完整触发器/动作/作者/运行账户），CSV 导出，操作历史记录",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "6.1",
    "date": "2026-07-23",
    "content": "网络连接查看器（TCP/UDP 全量连接，关联进程，筛选/自动刷新/结束进程/释放端口/导出CSV）",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "6.0",
    "date": "",
    "content": "快捷命令面板：全局热键 Ctrl+Alt+P 呼出浮层（窗口在后台时自动唤起到前台），模糊搜索工具名/关键词/描述/ID 一键跳转，加权排序，键盘导航（↑↓ 选择/Enter 跳转/Esc 关闭），应用内 Ctrl+P toggle，快捷键设置面板支持自定义，复用 shortcuts 表特殊 id `__palette__`",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "5.9",
    "date": "",
    "content": "Hosts 文件管理器：表格行内编辑（启用/IP/域名/备注）、多 Profile 切换（dev/test 一键切换，自动备份当前）、自动备份恢复（最近 20 份，预览/恢复/删除）、管理员权限检测、原子写入、路径遍历防御",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "5.8",
    "date": "",
    "content": "全局快捷键占用查看器：基于 RegisterHotKey 试探+立即释放探测 Windows 已注册全局热键，标注占用进程/应用，三级回退定位（映射表→进程扫描→LitoBox 自身），常见热键集+自定义补充，进入页面自动探测，事件+2s轮询兜底，CSV 导出，操作历史记录",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "5.7",
    "date": "",
    "content": "视频工具增强：视频变速（0.25x~4x，保持音调可选）、视频旋转翻转（90°/180°/270°，水平/垂直翻转）、音量调整（静音/+dB/-dB，快捷预设），统一整合到\"视频调整\"Tab，操作历史记录",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "5.6",
    "date": "",
    "content": "Windows 服务管理：系统服务列表查看，服务名/显示名称搜索，状态筛选，启动/停止/重启操作（需管理员权限），操作历史记录",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "5.5",
    "date": "",
    "content": "媒体信息查看器：ffprobe 深度分析媒体文件，展示容器格式、视频流/音频流/字幕流/元数据/章节信息，内嵌封面图提取预览（点击放大），专业参数中文 tooltip 说明，仅 ffmpeg 模式可用",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "5.4.1",
    "date": "",
    "content": "文字转语音（TTS）：SAPI 经典引擎 + WinRT 神经语音双引擎，系统语音列表自动发现，语速/音量可调，默认保存到下载目录，支持试听和打开所在文件夹",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "5.4",
    "date": "",
    "content": "音频工具扩展：格式转换（MP3/WAV/M4A/FLAC/OGG 互转）、音频压缩（目标比特率/质量等级）、音频合并（多文件拼接+拖拽排序）、变速变调（0.5x~4.0x，保持音调可选），均仅 ffmpeg 模式可用",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "5.3",
    "date": "",
    "content": "视频工具扩展：视频转码（格式/编码器/分辨率/帧率/比特率可调）、音频提取（MP3/AAC/WAV/FLAC/OGG）、视频压缩（CRF/预设/编码器可调）、视频合并（多文件拼接），均仅 ffmpeg 模式可用",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "5.2",
    "date": "",
    "content": "视频工具：MP4 视频裁剪（关键帧无损裁剪），缩略图时间轴可视化，滑块拖拽选区间，ffmpeg 可选增强",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "5.1",
    "date": "",
    "content": "PDF 压缩：3档预设（快速/标准/极限）+ 批量处理，纯 Rust 后端（lopdf + image crate），Ghostscript 可选增强",
    "isEnhancement": true,
    "isNewFeature": false
  },
  {
    "version": "5.0",
    "date": "",
    "content": "音频裁剪工具：支持 MP3/WAV 单段裁剪，Canvas 波形可视化 + 滑块拖拽，Web Audio API 实时预览，ffmpeg 运行时探测加速，自定义导出路径，裁剪进度条展示",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.9",
    "date": "",
    "content": "模板拼图：CSS Grid 预设布局模板 + 原生拖拽交换，支持 10 种模板、图片缩放/平移、透明背景",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.8",
    "date": "",
    "content": "图标生成器：一张图生成多尺寸 PNG 图标和 .ico 文件，支持 Favicon / App Icon 预设",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "4.7",
    "date": "",
    "content": "系统工具后台采集：系统信息/网络/进程/硬件/软件 5 个采集页改为后台线程采集，采集期间不卡 UI、可切换其他工具，完成后应用内通知提示，点击跳回原页",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.6",
    "date": "",
    "content": "全文搜索工具（文件名/内容双模式、正则表达式、进度取消、编码自动识别 UTF-8/GBK/UTF-16）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.5",
    "date": "",
    "content": "多 Tab 导航模式（顶部 Tab 栏、同时打开多个工具、KeepAlive 状态保留、右键菜单关闭其他/全部、LRU 上限 8 个）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.4",
    "date": "",
    "content": "进程 kill 与端口释放（ProcessListView 加结束按钮、NetworkInfoView 监听端口加释放按钮，共享 kill_process 后端命令）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.3",
    "date": "",
    "content": "磁盘空间分析器（文件夹大小/大文件Top N/按类型统计/重复文件检测，可入回收站删除）",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.2",
    "date": "",
    "content": "OCR/PDF/QR 结果支持编辑校正、PDF 转 Markdown（文本提取+OCR双模式）、PDF 文本提取保留段落换行",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "4.1",
    "date": "",
    "content": "SQLite 查看器（只读查询/表结构/CSV导出/历史记录）",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "4.0",
    "date": "",
    "content": "系统工具集（系统信息/网络信息/进程列表/硬件外设/软件环境）、侧边栏固定工具置顶",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "3.2",
    "date": "",
    "content": "计算器工具（表达式/单位换算/日期）、PDF↔OCR 工具联动、页面缓存 KeepAlive、编辑器明暗跟随系统",
    "isEnhancement": false,
    "isNewFeature": true
  },
  {
    "version": "3.1",
    "date": "",
    "content": "历史记录增强（完整数据存储、双击跳转恢复、参数还原）、文本编辑器（CodeMirror 6 内核）",
    "isEnhancement": true,
    "isNewFeature": true
  },
  {
    "version": "3.0",
    "date": "",
    "content": "SQLite 数据持久化、HTTP 环境变量/收藏/历史、快捷键自定义",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "2.x",
    "date": "",
    "content": "30+ 工具，OCR/PDF/Markdown/颜色/密码等",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "1.3",
    "date": "",
    "content": "文本对比工具",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "1.2",
    "date": "",
    "content": "SQL/JS执行器/Mock/OCR/文件编码",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "1.1",
    "date": "",
    "content": "操作历史/窗口置顶/主题切换",
    "isEnhancement": false,
    "isNewFeature": false
  },
  {
    "version": "1.0",
    "date": "",
    "content": "JSON/字符串/编码/正则/进制/UUID",
    "isEnhancement": false,
    "isNewFeature": false
  }
]
}
